Repository technoph1le/quicksnip, pull requests merged in 2024-12, with the labels that each got.

#2 Use Escape key to close snippet modal
  src/components/SnippetModal.tsx
  src/hooks/useEscapeKey.ts
Labels: enhancement

#36 ✨ Add utility functions and snippets to javascript.json
  public/data/javascript.json
Labels: Snippets

#15 Added Shuffle Array function
  public/data/javascript.json
Labels: Snippets

#40 Added a few python snippets for Sqlite and Json, aswell as a Button snippet for CSS
  public/data/css.json
  public/data/python.json
Labels: update needed, Snippets

#17 Added Hello, World! example to Python, Rust, Javascript and C++
  public/data/cpp.json
  public/data/javascript.json
  public/data/python.json
  public/data/rust.json
Labels: good first issue, discuss, Snippets

#29 Add string utility functions: count vowels, check anagram, and remove punctuation
  public/data/python.json
Labels: update needed, Snippets

#49 Add more JavaScript snippets
  public/data/javascript.json
Labels: update needed

#37 [find file/python] fixed snippet perf issue
  public/data/python.json
Labels: Snippets

#51 Add JavaScript snippets
  public/data/javascript.json
Labels: Snippets

#50 Added CSS snippet for grid layout
  public/data/css.json
Labels: update needed, Snippets

#44 Add HTML
  public/data/_index.json
  public/data/html.json
  public/icons/html5.svg
Labels: update needed, Snippets

#52 Add snippets for Javascript and C
  public/data/_index.json
  public/data/c.json
  public/data/javascript.json
  public/data/rust.json
  public/icons/c.svg
Labels: update needed, Snippets

#54 Add Python snippets
  public/data/python.json
Labels: update needed, Snippets

#55 Add a random string generator for javascript
  public/data/javascript.json
Labels: update needed, Snippets

#60 Add JavaScript snippets
  public/data/javascript.json
Labels: update needed, Snippets
